import type { TechnicalExperience } from "./types";

export const technicalExperience: TechnicalExperience[] = [
	{
		technology: "Astro",
		description: "JS framework that I learnt overnight to build this website",
		icon: "skill-icons:astro",
		tags: ["web"],
		expertiseRating: 5,
		preferenceRating: 4,
		projects: [],
	},
	{
		technology: "JavaScript",
		description:
			"General-purpose OOP programming language for the web, mobile and server",
		icon: "skill-icons:javascript",
		tags: ["programming language", "web", "mobile", "desktop", "backend"],
		expertiseRating: 5,
		preferenceRating: 4,
		projects: [
			"Countless web applications",
			"Wowzi Technologies frontend (web and mobile)",
		],
	},
	{
		technology: "TypeScript",
		description: "A type-safe version of JS",
		icon: "skill-icons:typescript",
		tags: ["programming language", "web", "mobile", "desktop", "backend"],
		expertiseRating: 5,
		preferenceRating: 5,
		projects: [
			"Countless web applications",
			"Wowzi Technologies frontend (web and mobile)",
		],
	},

	{
		technology: "Go",
		icon: "skill-icons:golang",
		tags: ["programming language", "backend"],
		description: "The best programming language ever made",
		expertiseRating: 5,
		preferenceRating: 5,
		projects: [
			"BF language parser",
			"Multiple servers",
			"CLI-based notes-taking application",
		],
	},
	{
		technology: "C",
		description: "Low level systems programming",
		icon: "skill-icons:c",
		tags: ["programming language", "systems"],
		expertiseRating: 4,
		preferenceRating: 3,
		projects: [
			"Clone of the tar file compression software",
			"File system (school project)",
		],
	},
	{
		technology: "Rust",
		icon: "skill-icons:rust",
		tags: ["programming language", "backend"],
		description:
			"Rust is a multi-paradigm, general-purpose programming language for high and low-level programming",
		expertiseRating: 2,
		preferenceRating: 1,
		projects: [],
	},
	{
		technology: "Python",
		icon: "skill-icons:python-dark",
		tags: ["programming language", "data science"],
		description:
			"High level programming language, best known for data science stuff",
		expertiseRating: 4,
		preferenceRating: 1,
		projects: [],
	},
	{
		technology: "MongoDB",
		icon: "skill-icons:mongodb",
		tags: ["database management", "database"],
		description: "Document-oriented database",
		expertiseRating: 5,
		preferenceRating: 4,
		projects: ["CMS", "POS system"],
	},
	{
		technology: "MySQL",
		icon: "skill-icons:mysql-dark",
		tags: ["database"],
		description: "Relations Database Management System",
		expertiseRating: 4,
		preferenceRating: 4,
		projects: [],
	},
	{
		technology: "Postgresql",
		icon: "skill-icons:postgresql-dark",
		tags: ["database"],
		description: "Relations Database Management System",
		expertiseRating: 2,
		preferenceRating: 5,
		projects: ["f-otm"],
	},
	{
		technology: "Java",
		icon: "skill-icons:java-dark",
		tags: ["programming language", "backend", "mobile"],
		description:
			"General purpose programming language for mobile and backend applications",
		expertiseRating: 5,
		preferenceRating: 3,
		projects: ["3D JavaFX rendering", "JavaFX Calculator", "Redis/MySQL server"],
	},
	{
		technology: "Flutter",
		icon: "skill-icons:flutter-dark",
		tags: ["mobile", "cross-platform"],
		description: "Performant UI library written in the dart programming language",
		expertiseRating: 3,
		preferenceRating: 4,
		projects: ["Din (Quran and Sunna) mobile application"],
	},
	{
		technology: "React / React Native",
		icon: "skill-icons:react-dark",
		tags: ["web", "mobile", "cross-platform"],
		description:
			"UI library and JS-to-Native bridge for web and mobile applications",
		expertiseRating: 5,
		preferenceRating: 3,
		projects: ["Din's initial prototype", "Wowzi Creator App"],
	},
	{
		technology: "Svelte",
		icon: "skill-icons:svelte",
		tags: ["web", "mobile", "cross-platform"],
		description: "Declarative JS compiler that supports true reactivity",
		expertiseRating: 5,
		preferenceRating: 5,
		projects: [
			"Din's NativeScript prototype",
			"Most of my web-based projects (SvelteKit)",
		],
	},
	{
		technology: "Vue",
		icon: "skill-icons:vuejs-dark",
		tags: ["web", "cross-platform"],
		description: "'Reactive' JS framework",
		expertiseRating: 5,
		preferenceRating: 4,
		projects: ["Wowzi advertiser platform"],
	},
	{
		technology: "Tauri",
		icon: "skill-icons:tauri-dark",
		tags: ["desktop", "cross-platform"],
		description:
			"Rust-based webview implementation (ElectronJS best alternative)",
		expertiseRating: 2,
		preferenceRating: 5,
		projects: [],
	},
	{
		technology: "Tailwind",
		icon: "skill-icons:tailwindcss-dark",
		tags: ["design", "web"],
		description: "CSS pre-processor",
		expertiseRating: 5,
		preferenceRating: 5,
		projects: ["Most of my web-based projects", "React Native + NativeWind"],
	},
	{
		technology: "Sassy CSS",
		icon: "skill-icons:sass",
		tags: ["design", "web"],
		description: "CSS pre-processor",
		expertiseRating: 4,
		preferenceRating: 4,
		projects: ["Wowzi web"],
	},
	{
		technology: "Figma",
		icon: "skill-icons:figma-dark",
		tags: ["design"],
		description: "Vector graphics editing and UI/UX prototyping software",
		expertiseRating: 3,
		preferenceRating: 3,
		projects: [],
	},
	{
		technology: "I use Arch BTW!",
		icon: "skill-icons:linux-dark",
		tags: ["desktop", "systems", "open-source"],
		description:
			"ArchLinux is a lightweight and flexible Linux distribution that is known for its performance and customization options.",
		expertiseRating: 4,
		preferenceRating: 5,
		projects: ["Daily driver"],
	},
];
